### ISSUE TITLE
Choose between 12 hour format, 24 hour format, or both (default)

### ISSUE THREAD

**Issue by ricardofbarros** [weareoutman/clockpicker#13]
I would like to choose the layout of the clock to show only 12 hours, 24 hours or both (like it's done), I'm going to fork it If I can make an workaround

**Comment by ricardofbarros** [comment]
Stupid question, I'm going to close, There isn't space to put 24 numbers in a row :)

**Comment by svaldenegro** [comment]
There's sufficient space to put it dividing the 1 segment in two.
