### ISSUE TITLE
doesnt work in canary 36

### ISSUE THREAD

**Issue by vprimachenko** [weareoutman/clockpicker#4]
nor click nor drag works in canary 36. can anyone confirm?

**Comment by weareoutman** [comment]
I didn't test chrome canary before.
I have just downloaded and tested, and it works fine.
Did you turned the **device emulation** on, or something?

**Comment by vprimachenko** [comment]
nope, yet it do work in an older chrome i have in my laptop when i turn touch-event emulation on

**Comment by weareoutman** [comment]
I just can't reproduce the issue.
Could you try to visit the qunit test page: http://weareoutman.github.io/clockpicker/test/all.html ?

**Comment by vprimachenko** [comment]
> Tests completed in 738 milliseconds.
> 78 assertions of 78 passed, 0 failed.

**Comment by weareoutman** [comment]
In Mac OSX or Windows ?

**Comment by vprimachenko** [comment]
Windows 7

**Comment by weareoutman** [comment]
Um, I'll test it in canary for windows tomorrow.
Thanks for reporting the issue. ;)

**Comment by vprimachenko** [comment]
ok fault is on my side, the leap motion driver installs an touch emulation driver, which is detected and the plugin set ups handler for `touchbegin` and `touchend` which i cant trigger with the mouse
