### ISSUE TITLE
'onclick' does not open a dialog when an input is focused

### ISSUE THREAD

**Issue by 3DFace** [weareoutman/clockpicker#6]
For example, if `autoclose` is on, when you selected a time, a focus is left in the input. If you click the input again, nothing happens. You have to remove focus manually (click somewhere out of the input) to make it work.
Seems like `onclick` does not toggle popup at all. Only `onfocus` works.

**Comment by gitlost** [comment]
Yeah it's a simple change, at least to get it popup again, by just adding 'click.clockpicker' to the 'focus.clockpicker' bind. I've put it in my pull request. This doesn't make it toggle though, which is a bit trickier to implement (have to keep some state so as to not immediately hide it after a focus), but it's better I think than the current situation.

**Comment by weareoutman** [comment]
Fixed by @gitlost #5
