### ISSUE TITLE
Option to disable mobile device native keyboard?

### ISSUE THREAD

**Issue by ravenjam** [weareoutman/clockpicker#60]
Is there an option to disable mobile device native keyboard support for the input fields?

**Comment by ravenjam** [comment]
Just realized my configuration is incorrect, sorry

**Comment by Slinf** [comment]
What was your problem ?? On my wab app the android keyboard is still runing when i choose hour with the clockpicker.

**Comment by Slinf** [comment]
Ok guys, i try a lot of solution. For me the only one who run is -->

```
$('input').on('focus', function() { $(this).blur(); });
```

--> I hope this will help anybody :)
