### ISSUE TITLE
How minute step fixed on 5

### ISSUE THREAD

**Issue by Slinf** [weareoutman/clockpicker#73]
Hi, i would fixed a step 5 by 5 min , like the minute on the display not between like 16min or 54 just 05-00-05-10-15-20-25-30-35-40-45-50-55-. I search in jquery.clockpicker-min.js  but its hard; If anybody know how//

i have check he other post on 30 minute step and doesb't run for me

Thanks

**Comment by patapron** [comment]
+1

**Comment by Chrumo** [comment]
+1

**Comment by PhiLhoSoft** [comment]
Duplicate of #51
